/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module lelel (
  input ON,
  input R0,
  output O2,
  output O1
);
  assign O2 = (R0 & ON);
  assign O1 = (~ R0 & ON);
endmodule

module \4RandomNumberGenerator  (
  input R0,
  input R1,
  input R2,
  output O4,
  output O3,
  output O2,
  output O1
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  lelel lelel_i0 (
    .ON( 1'b1 ),
    .R0( R0 ),
    .O2( s0 ),
    .O1( s1 )
  );
  lelel lelel_i1 (
    .ON( s1 ),
    .R0( R1 ),
    .O2( s2 ),
    .O1( s3 )
  );
  lelel lelel_i2 (
    .ON( s0 ),
    .R0( R1 ),
    .O2( s4 ),
    .O1( s5 )
  );
  lelel lelel_i3 (
    .ON( s3 ),
    .R0( R2 ),
    .O2( s6 ),
    .O1( O4 )
  );
  lelel lelel_i4 (
    .ON( s4 ),
    .R0( R2 ),
    .O2( O1 ),
    .O1( s7 )
  );
  assign s8 = (s5 | s2);
  lelel lelel_i5 (
    .ON( s8 ),
    .R0( R2 ),
    .O2( s9 ),
    .O1( s10 )
  );
  assign O3 = (s10 | s6);
  assign O2 = (s7 | s9);
endmodule
